### ISSUE TITLE
Changer le titre et le logo du site

### ISSUE THREAD

**Issue by snipzer** [katsenkatorz/ProjetIMIE#127]

**Comment by katsenkatorz** [comment]
On en reparle enssemble

**Comment by CMaxime** [comment]
Je pense qu'il vaut mieux abandonner le logo. J'ai pas le temps en 15 jours de me former sur illustrator. De plus, il nous faudrait un graphiste pour le faire.
Je vais repasser le titre avec la font du logo en attendant

**Comment by katsenkatorz** [comment]
C'est pas que l'on en as besoin car c'est hors limite du projet le logo nJob
