### ISSUE TITLE
CRUD Job

### ISSUE THREAD

**Issue by snipzer** [katsenkatorz/ProjetIMIE#20]
Faire:
-GetJobs()
-GetJobById(jobId)
-GetJobByLabel(label)
-PostJob(label, minSalary, maxSalary, description)
-PutJob(jobId, label, minSalary, maxSalary, description)
-DeleteJob(jobId)

**Comment by katsenkatorz** [comment]
A partir de l'administration en étant logué l'utilisateur doit pouvoir ajouter un métier.
Les champs sont donc remplie, 
Nom du métier | varchar
Déscription  | varchar
SalaireMin | int
SalaireMax| int

**Comment by katsenkatorz** [comment]
Je ne vois pas la fonctionnalité sur la V1
