### ISSUE TITLE
Seconde fonctionnalité

### ISSUE THREAD

**Issue by katsenkatorz** [katsenkatorz/ProjetIMIE#24]
Suite à l'ajout de métier on lui ajoute les types de personnalités
Pour un métier X on lui renseigne tout les types disponibles
Règle :
Un métier est lié à plusieurs personnalités métier et un type de personnalité n'est lié qu'a un seul métier.
Un type de personnalité est lié a plusieurs personnalité métier et une personnalité métier n'est lié qu'a un seul type de personnalité.
Un type de personnalité est constitué d'un nom et d’homonyme par exemple 
  Nom : Identité | varchar
  Trait de personnalité : Assuré | varchar
  Trait de personnalité opposé: Prudent | varchar
![sans titre](https://user-images.githubusercontent.com/5629437/27360087-89debd1c-561f-11e7-88e1-3046a7349186.png)

Une personnalité métier est constitué de deux clé secondaire
et d'une valeur exemple: 78 | INT qui est comprise entre 0 et 100 car %

Exemple de l'attendu technique :
![sans titre2](https://user-images.githubusercontent.com/5629437/27360320-aa11946e-5620-11e7-82f5-3e0996b552c7.png)

**Comment by snipzer** [comment]
Dépendant de #31 #10 #30 #20 et #34
