### ISSUE TITLE
CRUD JobPersonnality

### ISSUE THREAD

**Issue by snipzer** [katsenkatorz/ProjetIMIE#30]
Faire:
-GetJobPersonnalities()
-GetJobPersonnalityById(jobPersonnalityId)
-PostJobPersonnality(Job, PersonnalityType)
-PutJobPersonnality(jobPersonnalityId, PersonnalityType, Job)
-DeleteJobPersonnality(jobPersonnalityId)

**Comment by katsenkatorz** [comment]
Je ne vois pas la fonctionnalité sur la V1
