### ISSUE TITLE
CRUD PersonnalityType

### ISSUE THREAD

**Issue by snipzer** [katsenkatorz/ProjetIMIE#31]
Faire:
-GetPersonnalityTypes()
-GetPersonnalityTypeById(personnalityTypeId)
-GetPersonnalityTypeByName(name)
-PostPersonnalityType(name, personnalityType, opposedPersonnalityType)
-PutPersonnalityType(personnalityTypeId, name, personnalityType, opposedPersonnalityType)
-DeletePersonnalityType(personnalityTypeId)

**Comment by katsenkatorz** [comment]
Je ne vois pas la fonctionnalité sur la V1

**Comment by snipzer** [comment]
C'est normal cette issue est juste pour le CRUD de l'entité, pour faire la fonctionnalité j'ai besoin des deux autre CRUD et de l'issue #34 . Je fait sa se matin normalement.
