### ISSUE TITLE
3 eme fonctionnalité Question / réponse

### ISSUE THREAD

**Issue by katsenkatorz** [katsenkatorz/ProjetIMIE#39]
Sur le même principe que la seconde #24.
![sans titre](https://user-images.githubusercontent.com/5629437/27520270-5b2485f6-5a07-11e7-9f7a-27ba71528fbf.jpg)

Pour ce ticket cela va être simple c'est la même chose, ou presque. On complexifie légèrement, mais le principe reste le même. 
-	Création d’une question via une modal bootstrap (la liste de question est dans un accordions)
-	Lors de l’ouverture, chargement de la liste des réponses associé à la question et également un bouton ajout d’une réponse.
-	Le clique sur ajout de réponse ouvre une modale bootsrap avec le formulaire d’ajout de réponse.
-	L’ajout de réponse n’actualise pas la page, elle ferme la modal et l’ajoute à liste des réponses
-	Les champs : 
o	Libellé de la réponse
o	Combox du type de personnalité, la combobox provoque un évènement on change qui charge le champ suivant en fonction de sa valeur. (Ajax qui affiche les données pour l’input suivant Homonyme + opposé, c’est utile que pour l’affichage)
o	Input de type range définis la valeur de la réponse pour le type de personnalité choisie. 
o	Input image (pour le moment ne t’occupe pas de l’ajout d’image sa fera un ticket à part entière) 
![admin - gestion question](https://user-images.githubusercontent.com/5629437/27520717-a04a627c-5a11-11e7-99b1-11027b43eab9.png)
![admin - gestion question ajout](https://user-images.githubusercontent.com/5629437/27520720-a4270da0-5a11-11e7-95a9-667a1f606273.png)
![admin - gestion reponses](https://user-images.githubusercontent.com/5629437/27520724-b43c403e-5a11-11e7-8145-68ecea91b39c.png)
![admin - gestion reponse ajout](https://user-images.githubusercontent.com/5629437/27520721-a7d9e6b6-5a11-11e7-878f-473ceefba542.png)

**Comment by snipzer** [comment]
Manque l'appel en ajax pour afficher les homonymes

**Comment by katsenkatorz** [comment]
Oui j'ai vu hier, c'est simple maintenant tu es un pro de l'ajax :dancer:
