### ISSUE TITLE
Serveur

### ISSUE THREAD

**Issue by katsenkatorz** [katsenkatorz/ProjetIMIE#71]
Demande du serveur :
 - PHP 7
 - Mysql
 - Nginx ou Apache
 - Connection SSH
 - Upload du site en FTP

**Comment by snipzer** [comment]
On a transmis à Thierry(Admin système) et François-Xavier(Formateur), ils auraient besoin de plus d'information:
-Pour combien de temps ?
-Sur un bac à sable ou production ?
Il faut envoyer un mail à Thierry si on le met en production, et à François-Xavier si on le met sur le bac à sable. En mettant en cc Daniel ou Vincent.

**Comment by katsenkatorz** [comment]
J'envoie un mail je vous met en copy
