### ISSUE TITLE
Prospection des méthodes de partage Facebook

### ISSUE THREAD

**Issue by katsenkatorz** [katsenkatorz/ProjetIMIE#94]
https://developers.facebook.com/docs/sharing/reference/share-dialog
https://developers.facebook.com/docs/plugins/share-button?locale=fr_FR

**Comment by CMaxime** [comment]
Nos besoins : 
- Un compte facebook
- Un site en production

**Comment by katsenkatorz** [comment]
Suite à ton retour :
-  Cela prend 1 min pour créer un compte de test 0 si tu as un compte fb (je prend note pour demander à l'imie un compte pour la prod).
- Non pas obligatoire

**Comment by CMaxime** [comment]
- Creation d'un gmail de test / compte facebook
- Suivi du tutoriel d'implémentation du bouton "partager"
