### ISSUE TITLE
Implémentation du plugin facebook

### ISSUE THREAD

**Issue by katsenkatorz** [katsenkatorz/ProjetIMIE#95]

**Comment by CMaxime** [comment]
Comme précisé sur leur documentation, il nous faut posséder un compte facebook developers et un site en ligne (au moins connaître les noms des futurs urls du site) afin d'implémenter un "sharer" facebook. 
J'ai cependant ajouté le code dont nous avions besoin (de simples copier/coller fournis par la doc).

**Comment by katsenkatorz** [comment]
Je le laisse ouvert car il doit fonctionner en production

**Comment by katsenkatorz** [comment]
<img width="1680" alt="capture d ecran 2017-08-08 a 01 43 19" src="https://user-images.githubusercontent.com/5629437/29050284-41e6b2d0-7bdb-11e7-8442-7d4de7ab52c4.png">

Le partage doit être comme sa

**Comment by katsenkatorz** [comment]
Pk tu la close ?

**Comment by CMaxime** [comment]
Au temps pour moi, c'est une erreur.
