### ISSUE TITLE
Résolution des bugs lot 1

### ISSUE THREAD

**Issue by katsenkatorz** [katsenkatorz/ProjetIMIE#96]

**Comment by snipzer** [comment]
Voir #82

**Comment by katsenkatorz** [comment]
Oui mais ce ticket fait partie du lot 2 contrairement à l'autre (millestone)

**Comment by katsenkatorz** [comment]
Faut le laisser dans in process

**Comment by katsenkatorz** [comment]
Correction footer a realiser http://matthewjamestaylor.com/blog/bottom-footer-demo.htm
